name: workflow dispatch

on:
  # workflow_dispatch:
  #   inputs:
  #     versionName:
  #       required: true
  #       description: "this version name workflow"
  # # repository_dispatch:
  # #   types: [test]
  push
  #   branches:
  #     - "main"
  # pull_request:
  #   branches:
  #     - "feature"
  #   types: [opened, closed]

jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
      - name: check node version
        run: node -v

      - name: before checkout action
        if: github.ref == 'refs/head/feature'
        run: ls
        shell: bash

      - name: checkout step
        uses: actions/checkout@v3
        
      - name: after checkout
        if: github.event.inputs.versionName == 'test'
        run: ls
        shell: bash
